### ISSUE TITLE
ホーム画面作成

### ISSUE THREAD

**Issue by Joy-Hamada** [tsukuba-cojt/ains-frontend#1]
<h1>目的</h1>
ユーザがログイン後一番最初に見るページを作りたい。

<h1>仕様</h1>
chakra ui で可能な限り描く。かっこよさより統一感を優先しよう。
<h2>上部バー</h2>
固定表示（スクロールしても移動しない）を実装する。<br>
ボタンは左からアイコン、HOME、GENERATE、SERCH、通知、アカウント（マイページ）<br>
アイコンとHOMEは押せばホーム画面に移動し、HOME画面にいるときはHOMEの表示が黒字に白文字、いない時は白地に黒文字。<br>
GENERATE は押せば画像生成画面に遷移する。<br>
SERCHは入力フォーム形式。<br>
通知はフォローされたことや自分の画像が保存された時とかに通知が来る。今のところはハリボテでいい。<br>
アカウントは押せばマイページに遷移する。<br>
<h2>画像表示</h2>
横４個で表示してスクロールすれば無限に画像が出るようにする。<br>
今のところは表示する順番は気にしなくて良い。<br>
保存された画像が正方形でなくとも正方形で表示する。<br>

<img width="573" alt="スクリーンショット 2023-05-24 14 39 41" src="https://github.com/tsukuba-cojt/ains-frontend/assets/131435536/12ea3737-0582-4eb3-a57d-2d7fc9e8a538">

**Comment by Hidetaro7** [comment]
- 固定レイアウト部分とスクロール領域を実装する必要がある
- デザインシステムを導入したほうが体裁など統一できる
- ボタンの機能、役割などの定義を明確にする必要があるのではないか
- CSSによって誰がレイアウトするのか、分担範囲など決まっているのか

**Comment by Joy-Hamada** [comment]
- [ ] 上部バーを実装する
- [ ] 画像表示部分を実装する
- [ ] データベースから画像を引っ張る
