### ISSUE TITLE
ヘッダーが隠れてしまう

### ISSUE THREAD

**Issue by Joy-Hamada** [tsukuba-cojt/ains-frontend#19]
**バグの説明**
スクロールするとヘッダーが隠れてしまう。

**再現手順**
以下の手順で問題が再現する方法を記述してください：
1. 
2. '....'をクリックする
3. '....'までスクロールする
4. エラーが表示される

**期待される動作**
期待される動作について、明確かつ簡潔に説明してください。

**スクリーンショット**
可能であれば、問題を説明するためのスクリーンショットを追加してください。

**デスクトップ（以下の情報を入力してください）:**
 - OS：[例：iOS]
 - ブラウザ：[例：chrome、safari]
 - バージョン：[例：22]

**スマートフォン（以下の情報を入力してください）:**
 - デバイス：[例：iPhone6]
 - OS：[例：iOS8.1]
 - ブラウザ：[例：標準ブラウザ、safari]
 - バージョン：[例：22]

**追加のコンテキスト**
問題に関する追加の情報があれば、ここに追記してください。

**Comment by fazerog02** [comment]
#17 で対応しました！
