### ISSUE TITLE
アイディアボックス内容表示

### ISSUE THREAD

**Issue by Joy-Hamada** [tsukuba-cojt/ains-frontend#22]
**概要**
アイディアボックスの中が見えるようにする

**目的**
アイディアボックスに入った画像を最新順で見えるようにする

**実装に必要なタスク**
- [x] その他の画像
- [x] 削除
- [x] アイディアの個数
- [x] アイディアボックス名
- [x] 画像表示
<img width="1436" alt="スクリーンショット 2023-06-09 17 01 06" src="https://github.com/tsukuba-cojt/ains-frontend/assets/131435536/3bb0095b-fbd5-4866-8237-d8ced13d76ef">

**Comment by itouuuu** [comment]
renameボタンを追加する

**Comment by itouuuu** [comment]
- [] 空欄で題名変更できないようにする
- [] エラー文の表示(題名を入力してください)
- [] modalに適用ボタンを作り押した場合のみ改名
- [] 名前の重複チェック(サーバー側も必要？)
